In [4]:
import os          

os.chdir('E:\python')

In [5]:
import pandas as pd

d = pd.read_csv('dataset_Facebook.csv', ';')    # Supply the file name (path)

d.head(10)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142

In [6]:
d.describe() #Среднее, макс, мин, медиана - 50% для всей таблицы

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [7]:
d.mode(numeric_only=True) #Мода для всей

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136393.0,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,182.0,431.0,1210.0,690,403.0,0.0,98.0,13.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,2232.0,6503.0,NaN,298.0,513.0,1284.0,704,NaN,NaN,NaN,14.0,39.0
2,NaN,NaN,NaN,NaN,NaN,NaN,2645.0,7004.0,NaN,319.0,599.0,2541.0,1228,NaN,NaN,NaN,NaN,75.0
3,NaN,NaN,NaN,NaN,NaN,NaN,2938.0,8533.0,NaN,322.0,652.0,2888.0,1640,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,3322.0,8745.0,NaN,335.0,719.0,3675.0,1674,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,3358.0,12735.0,NaN,374.0,730.0,4911.0,1722,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,3414.0,NaN,NaN,482.0,795.0,4935.0,2044,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,3528.0,NaN,NaN,503.0,889.0,5010.0,2124,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,3754.0,NaN,NaN,513.0,NaN,5732.0,2162,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,5280.0,NaN,NaN,642.0,NaN,NaN,2174,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,5290.0,NaN,NaN,NaN,NaN,NaN,2388,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,6692.0,NaN,NaN,NaN,NaN,NaN,2426,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,9528.0,NaN,NaN,NaN,NaN,NaN,2604,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,13544.0,NaN,NaN,NaN,NaN,NaN,2616,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,32208.0,NaN,NaN,NaN,NaN,NaN,2644,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2660,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2752,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2868,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3114,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3216,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3230,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3768,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5348,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5372,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7020,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7800,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8032,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8120,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20608,NaN,NaN,NaN,NaN,NaN

In [8]:
d.groupby(['Type']).describe() #По типу

                Category  Lifetime Engaged Users  \
Type
Link   count   22.000000               22.000000
       mean     1.136364              342.818182
       std      0.467563              340.174414
       min      1.000000               24.000000
       25%      1.000000              105.000000
       50%      1.000000              244.000000
       75%      1.000000              422.000000
       max      3.000000             1374.000000
Photo  count  426.000000              426.000000
       mean     1.917840              818.946009
       std      0.884007              868.447092
       min      1.000000                9.000000
       25%      1.000000              399.000000
       50%      2.000000              605.500000
       75%      3.000000              949.000000
       max      3.000000            11452.000000
Status count   45.000000               45.000000
       mean     2.022222             2040.222222
       std      0.398228             1351.996838
       min      1.000000              128.000000
       25%      2.000000             1151.000000
       50%      2.000000             1701.000000
       75%      2.000000             2675.000000
       max      3.000000             6164.000000
Video  count    7.000000                7.000000
       mean     1.000000             1707.000000
       std      0.000000             1174.786080
       min      1.000000              459.000000
       25%      1.000000              829.000000
       50%      1.000000             1779.000000
       75%      1.000000             2090.500000
       max      1.000000             3872.000000

              Lifetime People who have liked your Page and engaged with your post  \
Type
Link   count                                          22.000000
       mean                                          210.545455
       std                                           188.873030
       min                                            19.000000
       25%                                            92.250000
       50%                                           161.500000
       75%                                           251.750000
       max                                           788.000000
Photo  count                                         426.000000
       mean                                          507.305164
       std                                           399.972665
       min                                             9.000000
       25%                                           300.250000
       50%                                           403.000000
       75%                                           569.750000
       max                                          3430.000000
Status count                                          45.000000
       mean                                         1719.844444
       std                                          1083.684581
       min                                           101.000000
       25%                                           995.000000
       50%                                          1604.000000
       75%                                          2256.000000
       max                                          4376.000000
Video  count                                           7.000000
       mean                                          979.428571
       std                                           650.805362
       min                                           363.000000
       25%                                           503.000000
       50%                                           885.000000
       75%                                          1192.000000
       max                                          2218.000000

              Lifetime Post Consumers  Lifetime Post Consumptions  \
Type
Link   count                22.000000                   22.000000
       mean                292.681818                  374.090909
       std                 291.385261                  358.404787
       min                  23.000000                   26.000000
       25%                  84.750000                  120.000000
       50%                 205.000000                  290.000000
       75%                 355.750000                  472.750000
       max                1106.000000                 1345.000000
Photo  count               426.000000                  426.000000
       mean                690.431925                 1299.025822
       std                 731.712670                 1965.996628
       min                   9.000000                    9.000000
       25%                 335.000000                  513.000000
       50%                 528.500000                  827.000000
       75%                 832.250000                 1327.500000
       max               11328.000000                19779.000000
Status count                45.000000                   45.000000
       mean               1949.555556                 2838.866667
       std                1319.980433                 2075.419548
       min                  86.000000                  112.000000
       25%                1073.000000                 1512.000000
       50%                1599.000000                 2201.000000
       75%                2567.000000                 3420.000000
       max                5934.000000                 9237.000000
Video  count                 7.000000                    7.000000
       mean               1584.714286                 2600.142857
       std                1160.701471                 2296.643524
       min                 411.000000                  539.000000
       25%                 763.000000                 1197.500000
       50%                1643.000000                 2331.000000
       75%                1845.500000                 2804.500000
       max                3822.000000                 7327.000000

              Lifetime Post Impressions by people who have liked your Page  \
Type
Link   count                                       2.200000e+01
       mean                                        1.114859e+04
       std                                         8.888569e+03
       min                                         2.307000e+03
       25%                                         6.367750e+03
       50%                                         9.034500e+03
       75%                                         1.390375e+04
       max                                         4.233800e+04
Photo  count                                       4.260000e+02
       mean                                        1.642248e+04
       std                                         6.450149e+04
       min                                         5.670000e+02
       25%                                         3.695250e+03
       50%                                         5.498000e+03
       75%                                         9.823000e+03
       max                                         1.107833e+06
Status count                                       4.500000e+01
       mean                                        1.866427e+04
       std                                         7.521069e+03
       min                                         5.009000e+03
       25%                                         1.388700e+04
       50%                                         1.750200e+04
       75%                                         2.210300e+04
       max                                         3.784900e+04
Video  count                                       7.000000e+00
       mean                                        4.314986e+04
       std                                         3.107268e+04
       min                                         2.143600e+04
       25%                                         2.564450e+04
       50%                                         3.013100e+04
       75%                                         4.584550e+04
       max                                         1.075020e+05

              Lifetime Post Total Impressions  Lifetime Post Total Reach  \
Type
Link   count                     2.200000e+01                  22.000000
       mean                      2.872545e+04               18544.590909
       std                       5.004205e+04               21399.411331
       min                       3.094000e+03                1536.000000
       25%                       6.861500e+03                3878.000000
       50%                       9.773000e+03                7422.000000
       75%                       2.615375e+04               30938.000000
       max                       2.297330e+05               70912.000000
Photo  count                     4.260000e+02                 426.000000
       mean                      2.899450e+04               13137.814554
       std                       8.095792e+04               22877.787010
       min                       5.700000e+02                 238.000000
       25%                       5.390000e+03                3092.500000
       50%                       8.118500e+03                4675.000000
       75%                       1.701375e+04               10571.000000
       max                       1.110282e+06              180480.000000
Status count                     4.500000e+01                  45.000000
       mean                      2.424447e+04               13078.888889
       std                       9.929143e+03                5218.086371
       min                       7.509000e+03                3930.000000
       25%                       1.709900e+04                9232.000000
       50%                       2.084900e+04               11096.000000
       75%                       3.051400e+04               15816.000000
       max                       5.996400e+04               31136.000000
Video  count                     7.000000e+00                   7.000000
       mean                      1.026224e+05               51205.714286
       std                       1.018383e+05               48825.191031
       min                       3.023500e+04               13544.000000
       25%                       3.618150e+04               19144.000000
       50%                       5.695000e+04               30624.000000
       75%                       1.408545e+05               68488.000000
       max                       2.771000e+05              139008.000000

              Lifetime Post reach by people who like your Page  \
Type
Link   count                                         22.000000
       mean                                        6544.363636
       std                                         5960.612461
       min                                         1180.000000
       25%                                         3156.000000
       50%                                         5039.000000
       75%                                         8140.000000
       max                                        27232.000000
Photo  count                                        426.000000
       mean                                        6059.103286
       std                                         7819.018244
       min                                          236.000000
       25%                                         2100.250000
       50%                                         3110.000000
       75%                                         5577.000000
       max                                        51456.000000
Status count                                         45.000000
       mean                                        9908.577778
       std                                         3997.608572
       min                                         2410.000000
       25%                                         7360.000000
       50%                                         8980.000000
       75%                                        11792.000000
       max                                        21352.000000
Video  count                                          7.000000
       mean                                       17386.285714
       std                                         9861.583607
       min                                         9568.000000
       25%                                        12340.000000
       50%                                        14112.000000
       75%                                        17312.000000
       max                                        38720.000000

              Page total likes        Paid   Post Hour  Post Month  \
Type
Link   count         22.000000   22.000000   22.000000   22.000000
       mean      116363.181818    0.272727    5.727273    6.590909
       std        21459.767350    0.455842    3.930126    4.563406
       min        85979.000000    0.000000    2.000000    1.000000
       25%        98829.250000    0.000000    3.000000    3.000000
       50%       115396.000000    0.000000    4.000000    4.500000
       75%       138059.000000    0.750000    9.250000   11.750000
       max       138895.000000    1.000000   14.000000   12.000000
Photo  count        426.000000  425.000000  426.000000  426.000000
       mean      122354.171362    0.280000    7.997653    6.805164
       std        16324.528694    0.449528    4.413082    3.234676
       min        81370.000000    0.000000    1.000000    1.000000
       25%       109670.000000    0.000000    3.000000    4.000000
       50%       128032.000000    0.000000    9.000000    7.000000
       75%       136013.000000    1.000000   11.000000   10.000000
       max       139441.000000    1.000000   23.000000   12.000000
Status count         45.000000   45.000000   45.000000   45.000000
       mean      132647.044444    0.222222    7.244444    9.066667
       std         7902.145290    0.420437    3.926342    2.553073
       min       104070.000000    0.000000    2.000000    3.000000
       25%       131300.000000    0.000000    3.000000    7.000000
       50%       135713.000000    0.000000    9.000000   10.000000
       75%       138353.000000    0.000000   10.000000   12.000000
       max       139441.000000    1.000000   15.000000   12.000000
Video  count          7.000000    7.000000    7.000000    7.000000
       mean      135014.857143    0.571429    8.714286    9.571429
       std         4730.551709    0.534522    4.347961    2.299068
       min       126424.000000    0.000000    2.000000    6.000000
       25%       132835.000000    0.000000    6.500000    8.000000
       50%       137893.000000    1.000000   11.000000   11.000000
       75%       138111.000000    1.000000   11.000000   11.000000
       max       138895.000000    1.000000   13.000000   12.000000

              Post Weekday  Total Interactions     comment         like  \
Type
Link   count     22.000000           22.000000   22.000000    22.000000
       mean       4.272727           89.045455    2.818182    73.318182
       std        1.856310           95.720564    3.633657    85.746240
       min        1.000000            6.000000    0.000000     5.000000
       25%        3.000000           32.750000    0.000000    19.500000
       50%        4.500000           52.500000    1.500000    37.000000
       75%        6.000000          125.000000    4.000000   110.750000
       max        7.000000          420.000000   15.000000   379.000000
Photo  count    426.000000          426.000000  426.000000   425.000000
       mean       4.107981          216.579812    7.492958   182.611765
       std        2.056286          405.709232   22.522275   345.245233
       min        1.000000            0.000000    0.000000     0.000000
       25%        2.000000           71.250000    1.000000    57.000000
       50%        4.000000          122.000000    3.000000   100.000000
       75%        6.000000          225.000000    7.000000   186.000000
       max        7.000000         6334.000000  372.000000  5172.000000
Status count     45.000000           45.000000   45.000000    45.000000
       mean       4.577778          217.044444    8.911111   176.711111
       std        1.924588          178.479940   12.451400   150.772499
       min        1.000000           17.000000    0.000000    13.000000
       25%        3.000000          106.000000    2.000000    86.000000
       50%        5.000000          186.000000    4.000000   150.000000
       75%        6.000000          265.000000   10.000000   226.000000
       max        7.000000         1009.000000   60.000000   859.000000
Video  count      7.000000            7.000000    7.000000     7.000000
       mean       3.571429          295.857143   12.285714   231.428571
       std        1.511858          183.992236    8.693183   142.025652
       min        2.000000           81.000000    2.000000    65.000000
       25%        2.500000          144.000000    4.000000   121.000000
       50%        3.000000          271.000000   17.000000   204.000000
       75%        4.500000          440.500000   18.000000   330.000000
       max        6.000000          550.000000   23.000000   449.000000

                   share
Type
Link   count   22.000000
       mean    12.909091
       std     11.751025
       min      0.000000
       25%      5.500000
       50%     10.500000
       75%     15.000000
       max     44.000000
Photo  count  422.000000
       mean    27.158768
       std     44.919679
       min      0.000000
       25%     10.000000
       50%     19.000000
       75%     32.000000
       max    790.000000
Status count   45.000000
       mean    31.422222
       std     24.272589
       min      1.000000
       25%     16.000000
       50%     28.000000
       75%     39.000000
       max    123.000000
Video  count    7.000000
       mean    52.142857
       std     42.643595
       min     13.000000
       25%     13.500000
       50%     44.000000
       75%     80.000000
       max    121.000000

In [9]:
d.groupby(['Type']).apply(lambda x: x.mode()) #Мода для каждого из типов

           Page total likes    Type  Category  Post Month  Post Weekday  \
Type
Link   0           138353.0    Link       1.0        12.0           6.0
       1                NaN     NaN       NaN         NaN           NaN
Photo  0           124940.0   Photo       1.0        10.0           7.0
       1                NaN     NaN       NaN         NaN           NaN
       2                NaN     NaN       NaN         NaN           NaN
       3                NaN     NaN       NaN         NaN           NaN
       4                NaN     NaN       NaN         NaN           NaN
       5                NaN     NaN       NaN         NaN           NaN
       6                NaN     NaN       NaN         NaN           NaN
       7                NaN     NaN       NaN         NaN           NaN
       8                NaN     NaN       NaN         NaN           NaN
       9                NaN     NaN       NaN         NaN           NaN
       10               NaN     NaN       NaN         NaN           NaN
       11               NaN     NaN       NaN         NaN           NaN
       12               NaN     NaN       NaN         NaN           NaN
       13               NaN     NaN       NaN         NaN           NaN
       14               NaN     NaN       NaN         NaN           NaN
       15               NaN     NaN       NaN         NaN           NaN
       16               NaN     NaN       NaN         NaN           NaN
       17               NaN     NaN       NaN         NaN           NaN
       18               NaN     NaN       NaN         NaN           NaN
       19               NaN     NaN       NaN         NaN           NaN
       20               NaN     NaN       NaN         NaN           NaN
       21               NaN     NaN       NaN         NaN           NaN
       22               NaN     NaN       NaN         NaN           NaN
       23               NaN     NaN       NaN         NaN           NaN
       24               NaN     NaN       NaN         NaN           NaN
       25               NaN     NaN       NaN         NaN           NaN
       26               NaN     NaN       NaN         NaN           NaN
Status 0           139441.0  Status       2.0        12.0           5.0
       1                NaN     NaN       NaN         NaN           7.0
       2                NaN     NaN       NaN         NaN           NaN
       3                NaN     NaN       NaN         NaN           NaN
Video  0           137893.0   Video       1.0        11.0           2.0
       1                NaN     NaN       NaN         NaN           3.0

           Post Hour  Paid  Lifetime Post Total Reach  \
Type
Link   0         3.0   0.0                        NaN
       1         NaN   NaN                        NaN
Photo  0         3.0   0.0                      677.0
       1         NaN   NaN                     2232.0
       2         NaN   NaN                     2938.0
       3         NaN   NaN                     3322.0
       4         NaN   NaN                     3358.0
       5         NaN   NaN                     3414.0
       6         NaN   NaN                     3528.0
       7         NaN   NaN                     3754.0
       8         NaN   NaN                     5280.0
       9         NaN   NaN                     5290.0
       10        NaN   NaN                     9528.0
       11        NaN   NaN                    32208.0
       12        NaN   NaN                        NaN
       13        NaN   NaN                        NaN
       14        NaN   NaN                        NaN
       15        NaN   NaN                        NaN
       16        NaN   NaN                        NaN
       17        NaN   NaN                        NaN
       18        NaN   NaN                        NaN
       19        NaN   NaN                        NaN
       20        NaN   NaN                        NaN
       21        NaN   NaN                        NaN
       22        NaN   NaN                        NaN
       23        NaN   NaN                        NaN
       24        NaN   NaN                        NaN
       25        NaN   NaN                        NaN
       26        NaN   NaN                        NaN
Status 0        10.0   0.0                        NaN
       1         NaN   NaN                        NaN
       2         NaN   NaN                        NaN
       3         NaN   NaN                        NaN
Video  0        11.0   1.0                        NaN
       1         NaN   NaN                        NaN

           Lifetime Post Total Impressions  Lifetime Engaged Users  \
Type
Link   0                               NaN                    66.0
       1                               NaN                     NaN
Photo  0                            4372.0                   537.0
       1                            6503.0                     NaN
       2                            7004.0                     NaN
       3                            8533.0                     NaN
       4                            8745.0                     NaN
       5                           12735.0                     NaN
       6                               NaN                     NaN
       7                               NaN                     NaN
       8                               NaN                     NaN
       9                               NaN                     NaN
       10                              NaN                     NaN
       11                              NaN                     NaN
       12                              NaN                     NaN
       13                              NaN                     NaN
       14                              NaN                     NaN
       15                              NaN                     NaN
       16                              NaN                     NaN
       17                              NaN                     NaN
       18                              NaN                     NaN
       19                              NaN                     NaN
       20                              NaN                     NaN
       21                              NaN                     NaN
       22                              NaN                     NaN
       23                              NaN                     NaN
       24                              NaN                     NaN
       25                              NaN                     NaN
       26                              NaN                     NaN
Status 0                               NaN                     NaN
       1                               NaN                     NaN
       2                               NaN                     NaN
       3                               NaN                     NaN
Video  0                               NaN                     NaN
       1                               NaN                     NaN

           Lifetime Post Consumers  Lifetime Post Consumptions  \
Type
Link   0                     322.0                         NaN
       1                       NaN                         NaN
Photo  0                     298.0                       431.0
       1                     319.0                       513.0
       2                     335.0                       599.0
       3                     374.0                       652.0
       4                     482.0                       719.0
       5                     503.0                       730.0
       6                     513.0                       795.0
       7                     642.0                       889.0
       8                       NaN                         NaN
       9                       NaN                         NaN
       10                      NaN                         NaN
       11                      NaN                         NaN
       12                      NaN                         NaN
       13                      NaN                         NaN
       14                      NaN                         NaN
       15                      NaN                         NaN
       16                      NaN                         NaN
       17                      NaN                         NaN
       18                      NaN                         NaN
       19                      NaN                         NaN
       20                      NaN                         NaN
       21                      NaN                         NaN
       22                      NaN                         NaN
       23                      NaN                         NaN
       24                      NaN                         NaN
       25                      NaN                         NaN
       26                      NaN                         NaN
Status 0                       NaN                      1692.0
       1                       NaN                         NaN
       2                       NaN                         NaN
       3                       NaN                         NaN
Video  0                       NaN                         NaN
       1                       NaN                         NaN

           Lifetime Post Impressions by people who have liked your Page  \
Type
Link   0                                                 NaN
       1                                                 NaN
Photo  0                                              1210.0
       1                                              1284.0
       2                                              2541.0
       3                                              2888.0
       4                                              3675.0
       5                                              4911.0
       6                                              4935.0
       7                                              5010.0
       8                                              5732.0
       9                                                 NaN
       10                                                NaN
       11                                                NaN
       12                                                NaN
       13                                                NaN
       14                                                NaN
       15                                                NaN
       16                                                NaN
       17                                                NaN
       18                                                NaN
       19                                                NaN
       20                                                NaN
       21                                                NaN
       22                                                NaN
       23                                                NaN
       24                                                NaN
       25                                                NaN
       26                                                NaN
Status 0                                                 NaN
       1                                                 NaN
       2                                                 NaN
       3                                                 NaN
Video  0                                                 NaN
       1                                                 NaN

           Lifetime Post reach by people who like your Page  \
Type
Link   0                                                NaN
       1                                                NaN
Photo  0                                              690.0
       1                                              704.0
       2                                             1228.0
       3                                             1640.0
       4                                             1674.0
       5                                             1722.0
       6                                             2044.0
       7                                             2124.0
       8                                             2162.0
       9                                             2174.0
       10                                            2388.0
       11                                            2426.0
       12                                            2604.0
       13                                            2616.0
       14                                            2644.0
       15                                            2660.0
       16                                            2704.0
       17                                            2752.0
       18                                            2868.0
       19                                            3114.0
       20                                            3216.0
       21                                            3230.0
       22                                            3298.0
       23                                            3768.0
       24                                            5348.0
       25                                            7800.0
       26                                           20608.0
Status 0                                                NaN
       1                                                NaN
       2                                                NaN
       3                                                NaN
Video  0                                                NaN
       1                                                NaN

           Lifetime People who have liked your Page and engaged with your post  \
Type
Link   0                                                 NaN
       1                                                 NaN
Photo  0                                               403.0
       1                                                 NaN
       2                                                 NaN
       3                                                 NaN
       4                                                 NaN
       5                                                 NaN
       6                                                 NaN
       7                                                 NaN
       8                                                 NaN
       9                                                 NaN
       10                                                NaN
       11                                                NaN
       12                                                NaN
       13                                                NaN
       14                                                NaN
       15                                                NaN
       16                                                NaN
       17                                                NaN
       18                                                NaN
       19                                                NaN
       20                                                NaN
       21                                                NaN
       22                                                NaN
       23                                                NaN
       24                                                NaN
       25                                                NaN
       26                                                NaN
Status 0                                                 NaN
       1                                                 NaN
       2                                                 NaN
       3                                                 NaN
Video  0                                                 NaN
       1                                                 NaN

           comment   like  share  Total Interactions
Type
Link   0       0.0   12.0    2.0                14.0
       1       NaN   32.0    NaN                 NaN
Photo  0       0.0    7.0   14.0                 0.0
       1       NaN   79.0    NaN                39.0
       2       NaN   98.0    NaN                 NaN
       3       NaN    NaN    NaN                 NaN
       4       NaN    NaN    NaN                 NaN
       5       NaN    NaN    NaN                 NaN
       6       NaN    NaN    NaN                 NaN
       7       NaN    NaN    NaN                 NaN
       8       NaN    NaN    NaN                 NaN
       9       NaN    NaN    NaN                 NaN
       10      NaN    NaN    NaN                 NaN
       11      NaN    NaN    NaN                 NaN
       12      NaN    NaN    NaN                 NaN
       13      NaN    NaN    NaN                 NaN
       14      NaN    NaN    NaN                 NaN
       15      NaN    NaN    NaN                 NaN
       16      NaN    NaN    NaN                 NaN
       17      NaN    NaN    NaN                 NaN
       18      NaN    NaN    NaN                 NaN
       19      NaN    NaN    NaN                 NaN
       20      NaN    NaN    NaN                 NaN
       21      NaN    NaN    NaN                 NaN
       22      NaN    NaN    NaN                 NaN
       23      NaN    NaN    NaN                 NaN
       24      NaN    NaN    NaN                 NaN
       25      NaN    NaN    NaN                 NaN
       26      NaN    NaN    NaN                 NaN
Status 0       2.0   86.0    1.0               117.0
       1       4.0   99.0   13.0               121.0
       2       NaN  129.0   18.0                 NaN
       3       NaN  227.0   36.0                 NaN
Video  0       2.0    NaN   13.0                 NaN
       1      18.0    NaN    NaN                 NaN

In [13]:
d['Lifetime Engaged Users'].idxmax()

446

In [15]:
d.loc[446]

Page total likes                                                        96749
Type                                                                    Photo
Category                                                                    1
Post Month                                                                  3
Post Weekday                                                                1
Post Hour                                                                   2
Paid                                                                        1
Lifetime Post Total Reach                                               98816
Lifetime Post Total Impressions                                        125026
Lifetime Engaged Users                                                  11452
Lifetime Post Consumers                                                 11328
Lifetime Post Consumptions                                              18115
Lifetime Post Impressions by people who have liked your Page            16682
Lifetime Post reach by people who like your Page                        10336
Lifetime People who have liked your Page and engaged with your post      1356
comment                                                                    10
like                                                                      197
share                                                                      21
Total Interactions                                                        228
Name: 446, dtype: object